name: sdl2ui
description: This is a library to make sdl2 easier to use. Dependencies ffi, sdl2, archive.
version: 0.1.2
homepage: https://github.com/sansuido/sdl2ui
repository: https://github.com/sansuido/sdl2ui

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ffi: ^2.0.2
  sdl2: ^1.5.2
  archive: ^3.3.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
