name: sdl2ui
description: This is a library to make sdl2 easier to use. Dependencies ffi, sdl2, archive.
version: 0.1.4
homepage: https://github.com/sansuido/sdl2ui
repository: https://github.com/sansuido/sdl2ui

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.2
  sdl2: ^1.7.1
  archive: ^3.4.10

dev_dependencies:
  lints: ^3.0.0
